# Generated by Django 3.1.7 on 2021-06-06 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AyudaApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('dateofbirth', models.DateField(null=True)),
                ('street1', models.CharField(max_length=100, null=True)),
                ('street2', models.CharField(max_length=100, null=True)),
                ('personid', models.ImageField(null=True, upload_to='')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebigay.city')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebigay.region')),
            ],
        ),
    ]
