# Generated by Django 3.1.7 on 2021-06-06 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ebigay', '0003_auto_20210606_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayudaapplicant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
