# Generated by Django 3.1.7 on 2021-06-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebigay', '0006_ayudadropoff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.CharField(choices=[('NCR', 'National Capital Region'), ('CAR', 'Cordillera Administrative Region'), ('Region I', 'Ilocos Region'), ('Region II', 'Cagayan Valley Region'), ('Region III', 'Central Luzon Region'), ('Region IV-A', 'CALABARZON Region'), ('Region IV-B', 'MIMAROPA Region'), ('Region V', 'Bicol Region'), ('Region VI', 'Western Visayas Region'), ('Region VII', 'Central Visayas Region'), ('Region VIII', 'Eastern Visayas Region'), ('Region IX', 'Zamboanga Peninsula Region'), ('Region X', 'Northern Mindanao Region'), ('Region XI', 'Davao Region'), ('Region XII', 'SOCCSKARGEN Region'), ('Region XIII', 'Caraga Region'), ('BARMM', 'Bangsamoro Autonomous Region in Muslim Mindanao')], max_length=50, null=True),
        ),
    ]
